global:
  configMap:
    name: msa-config
  secret:
    name: msa-secret
globalIngress:
  enabled: true
  name: title # Ingress 이름
  className: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/load-balancer-arn: arn:aws:elasticloadbalancing:ap-northeast-2:490913547024:loadbalancer/app/GroomALb/5a0cf7788c5e52f7
    # alb.ingress.kubernetes.io/load-balancer-arn: arn:aws:elasticloadbalancing:ap-northeast-2:490913547024:loadbalancer/app/GroomALb/fca97ed8d82cc52e # 필요시 주석 해제
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]' # 리스너 포트
  # tls: # HTTPS를 사용하려면 여기에 TLS 설정 추가
services:
  user:
    enabled : true #이 서비스를 배포할 것인가?
    replicaCount : 2
    image:
      repository: 490913547024.dkr.ecr.ap-northeast-2.amazonaws.com/user-service
      tag: bc93aed
      pullPolicy : IfNotPresent
    service:
      type: ClusterIP
      port: 80
      targetPort: 8080
    
    # 카나리 배포 설정
    canary:
      enabled: true  # 카나리 배포 활성화
      initialWeight: 10  # 초기 트래픽 비율 (10%)
      middleWeight: 50   # 중간 트래픽 비율 (50%)
      pauseDuration: "30s"  # 각 단계별 대기 시간
      autoPromotionEnabled: false  # 자동 프로모션 비활성화 (수동 승인)
      analysis:
        enabled: false  # 메트릭 기반 분석 비활성화 (나중에 Prometheus 설정 후 활성화)
      trafficRouting:
        alb:
          ingress: title # globalIngress에서 정의한 단일 Ingress 이름

    ingress:
      enabled: true
      host: "" # 경로 기반 라우팅, 호스트 지정 안 함
      paths:
        - path: /user
          pathType: ImplementationSpecific

    livenessProbe:
      httpGet:
        path: /actuator/health
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
    
    readinessProbe:
      httpGet:
        path: /actuator/health/readiness
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

    env:
      - name: SPRING_PROFILES_ACTIVE
        value: "dev"

    resources:
      requests:
        cpu: 100m
        memory: 400Mi
      limits:
        cpu: 500m
        memory: 800Mi

  order:
    enabled: true #이 서비스를 배포할 것인가?
    replicaCount: 2
    image:
      repository: 490913547024.dkr.ecr.ap-northeast-2.amazonaws.com/order-service
      tag: 3f6c7f2
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 80
      targetPort: 8080

    resources:
      requests:
        cpu: 100m
        memory: 400Mi
      limits:
        cpu: 500m
        memory: 800Mi
    ingress:
      enabled: true
      host: ""
      paths:
        - path: /order
          pathType: ImplementationSpecific
  store:
    enabled : true #이 서비스를 배포할 것인가?
    replicaCount : 2
    image:
      repository: 490913547024.dkr.ecr.ap-northeast-2.amazonaws.com/store-service
      tag: 3f6c7f2
      pullPolicy : IfNotPresent
    service:
      type: ClusterIP
      port: 80
      targetPort: 8080

    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    ingress:
      enabled: true
      host: ""
      paths:
        - path: /store
          pathType: ImplementationSpecific
  auth:
    enabled: true #이 서비스를 배포할 것인가?
    replicaCount: 2
    image:
      repository: 490913547024.dkr.ecr.ap-northeast-2.amazonaws.com/auth-service
      tag: 9d15e96
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 80
      targetPort: 8080
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    ingress:
      enabled: true
      host: ""
      paths:
        - path: /auth
          pathType: ImplementationSpecific
  ai:
    enabled: true #이 서비스를 배포할 것인가?
    replicaCount: 2
    image:
      repository: 490913547024.dkr.ecr.ap-northeast-2.amazonaws.com/ai-service
      tag: 2554cd4
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 80
      targetPort: 8080
    resources:
      requests:
        cpu: 100m
        memory: 400Mi
      limits:
        cpu: 500m
        memory: 800Mi
    ingress:
      enabled: true
      host: ""
      paths:
        - path: /ai
          pathType: ImplementationSpecific

  payment:
    enabled: true #이 서비스를 배포할 것인가?
    replicaCount: 2
    image:
      repository: 490913547024.dkr.ecr.ap-northeast-2.amazonaws.com/payment-service
      tag: c2d0cf5
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 80
      targetPort: 8080

    resources:
      requests:
        cpu: 100m
        memory: 400Mi
      limits:
        cpu: 500m
        memory: 800Mi
    ingress:
      enabled: true
      host: ""
      paths:
        - path: /payment
          pathType: ImplementationSpecific
  common:
    enabled: true #이 서비스를 배포할 것인가?
    replicaCount: 2
    image:
      repository: 490913547024.dkr.ecr.ap-northeast-2.amazonaws.com/common-service
      tag: bc93aed
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 80
      targetPort: 8080

    resources:
      resources:
        requests:
          cpu: 100m
          memory: 400Mi
        limits:
          cpu: 500m
          memory: 800Mi
    ingress:
      enabled: true
      host: ""
      paths:
        - path: /common
          pathType: ImplementationSpecific

# ConfigMap configuration
configMap:
  enabled: true
  data:
    SPRING_PROFILES_ACTIVE: "dev"
    SERVER_PORT: "8080"
    # Add other config values as needed

# Secret configuration
secret:
  enabled: true
  stringData:
    DB_USERNAME: "YOUR_DB_USERNAME"
    DB_PASSWORD: "YOUR_DB_PASSWORD"
    REDIS_PASSWORD: "YOUR_REDIS_PASSWORD"
    OPENAI_API_KEY: "YOUR_OPENAI_API_KEY"
    MONGODB_URI: "YOUR_MONGODB_URI"
    MONGODB_NAME: "YOUR_MONGODB_NAME"


