apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  #  namespace: goormone-msa
  labels:
    app: ai-service
    component : msa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
        component: msa
    spec:
      # eks 에서만
      #      nodeSelector:
      #        node-type : app

      containers:
        - name: ai-service
          image: 490913547024.dkr.ecr.ap-northeast-2.amazonaws.com/ai-service:2554cd4
          #image: bleuxsy/ai-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http


          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: DB_USERNAME
              valueFrom:
                  secretKeyRef:
                    name: ai-service-secret
                    key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: ai-service-secret
                    key: DB_PASSWORD
            - name: OPENAI_API_KEY
              valueFrom:
                  secretKeyRef:
                    name: ai-service-secret
                    key: OPENAI_API_KEY
            - name: MONGODB_URI
              valueFrom:
                  secretKeyRef:
                    name: ai-service-secret
                    key: MONGODB_URI
            - name: MONGODB_NAME
              valueFrom:
                  secretKeyRef:
                    name: ai-service-secret
                    key: MONGODB_NAME
          #          envFrom:
          #            - configMapRef:
          #                name: msa-config
          #            - secretRef:
          #                name: msa-secret

#          resources:
#            requests:
#              cpu: 500m
#              memory: 512Mi
#            limits:
#              cpu: 1000m
#              memory: 1Gi
      #          livenessProbe:
      #            httpGet:
      #              path: /actuator/health/liveness
      #              port: 8080
      #            initialDelaySeconds: 60
      #            periodSeconds: 30
      #          readinessProbe:
      #            httpGet:
      #              path: /actuator/health/readiness
      #              port: 8080
      #            initialDelaySeconds: 30
      #            periodSeconds: 10
      restartPolicy: Always
      