apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
#  namespace: goormone-msa
  labels:
    app: auth-service
    component : msa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        component: msa
    spec:
      # eks 에서만
#      nodeSelector:
#        node-type : app

      containers:
        - name: auth-service
#          image: 490913547024.dkr.ecr.ap-northeast-2.amazonaws.com/auth-service:latest
          image: bleuxsy/auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: msa-config
            - secretRef:
                name: msa-secret

          resources:
              requests:
                cpu: 500m
                memory: 512Mi
              limits:
                cpu: 1000m
                memory: 1Gi
#          livenessProbe:
#            httpGet:
#              path: /actuator/health/liveness
#              port: 8080
#            initialDelaySeconds: 60
#            periodSeconds: 30
#          readinessProbe:
#            httpGet:
#              path: /actuator/health/readiness
#              port: 8080
#            initialDelaySeconds: 30
#            periodSeconds: 10
      restartPolicy: Always
      