apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goormone-msa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GoormOne/goormOne_kubernetes.git
    targetRevision: feat/argocd
    path: goormOne
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
