apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    # GitHub Actions 역할 (ECR)
    - rolearn: arn:aws:iam::490913547024:role/gitactionToECR
      username: github-actions
      groups:
        - system:masters

    # GitHub Actions 역할 (EKS)
    - rolearn: arn:aws:iam::490913547024:role/gitactionToEKS
      username: github-actions-eks
      groups:
        - system:masters

    # EKS 노드그룹 역할
    - rolearn: arn:aws:iam::490913547024:role/eksctl-Groom-EKS-Cluster-nodegroup-NodeInstanceRole
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::490913547024:role/Groom-EKS-Cluster-NodeInstanceRole
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::490913547024:role/EKSNodeGroupRole
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

  mapUsers: |
    # GitHub Actions AssumedRole (EKS)
    - userarn: arn:aws:sts::490913547024:assumed-role/gitactionToEKS/GitHubActions
      username: github-actions-assumed-eks
      groups:
        - system:masters
    - userarn : arn:aws:iam:490913547024:user/user1
      username : user1
      groups :
        - susmte:master
    - userarn : arn:aws:iam:490913547024:user/user2
          username : user2
          groups :
            - susmte:master
    - userarn : arn:aws:iam:490913547024:user/user3
          username : user3
          groups :
            - susmte:master
    - userarn : arn:aws:iam:490913547024:user/user4
          username : user4
          groups :
            - susmte:master
    - userarn : arn:aws:iam:490913547024:user/user0
          username : user0
          groups :
            - susmte:master
    - userarn : arn:aws:iam:490913547024:user/user5
          username : user5
          groups :
            - susmte:master