apiVersion: v1
kind: ConfigMap
metadata:
  name: msa-config
  namespace: goormone-msa
data:
  # Spring Boot 공통 설정
  SPRING_PROFILES_ACTIVE: "dev"
  SERVER_PORT: "8080"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  
  # Kafka 설정
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service.goormone-infra.svc.cluster.local:9092"
  KAFKA_CONSUMER_GROUP_ID: "goormone-msa-group"
  
  # Redis 설정
  REDIS_HOST: "redis-service.goormone-infra.svc.cluster.local"
  REDIS_PORT: "6379"
  
  # Database 설정 (필요시)
  DB_HOST: "rds-endpoint"
  DB_PORT: "5432"
  DB_NAME: "goormone_db"

---
apiVersion: v1
kind: Secret
metadata:
  name: msa-secret
  namespace: goormone-msa
type: Opaque
data:

  DB_USERNAME: postgres # goormone
  DB_PASSWORD: Goorm1!  # password
  REDIS_PASSWORD: ""         # Redis 비밀번호 없음


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-config
  namespace: goormone-logging
#data:
#  # FluentBit 설정
##  fluent-bit.conf: |
##    [SERVICE]
##        Flush         1
##        Log_Level     info
##        Daemon        off
##        Parsers_File  parsers.conf
##        HTTP_Server   On
##        HTTP_Listen   0.0.0.0
##        HTTP_Port     2020
##
##    [INPUT]
##        Name              tail
##        Path              /var/log/containers/*.log
##        Parser            docker
##        Tag               kube.*
##        Refresh_Interval  5
##        Mem_Buf_Limit     50MB
##        Skip_Long_Lines   On
##
##    [FILTER]
##        Name                kubernetes
##        Match               kube.*
##        Kube_URL            https://kubernetes.default.svc:443
##        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
##        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
##        Kube_Tag_Prefix     kube.var.log.containers.
##        Merge_Log           On
##        Keep_Log            Off
##        K8S-Logging.Parser  On
##        K8S-Logging.Exclude Off
##
##    [OUTPUT]
##        Name  http
##        Match *
##        Host  loki-service.goormone-logging.svc.cluster.local
##        Port  3100
##        URI   /loki/api/v1/push
#        Format json
#
#  parsers.conf: |
#    [PARSER]
#        Name   docker
#        Format json
#        Time_Key time
#        Time_Format %Y-%m-%dT%H:%M:%S.%L
#        Time_Keep   On
