apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: title
  annotations:
    kubernetes.io/ingress.class: alb
#    alb.ingress.kubernetes.io/load-balancer-arn: arn:aws:elasticloadbalancing:ap-northeast-2:490913547024:loadbalancer/app/GroomALb/fca97ed8d82cc52e
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/group.name: my-msa-group
    # Argo Rollouts 카나리 배포를 위한 어노테이션
    alb.ingress.kubernetes.io/actions.weighted-routing: |
      {
        "type": "forward",
        "forwardConfig": {
          "targetGroups": [
            {
              "serviceName": "user-service",
              "servicePort": "8080",
              "weight": 100
            }
          ]
        }
      }


spec:
  ingressClassName: alb
  rules:
    - http:

        paths:

          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  name: http
          - path: /common
            pathType: Prefix
            backend:
              service:
                name: common-service
                port:
                  name: http
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  name: http
          - path: /stores
            pathType: Prefix
            backend:
              service:
                name: store-service
                port:
                  name: http
          - path: /payments
            pathType: Prefix
            backend:
              service:
                name: payment-service
                port:
                  name: http
          - path: /ai
            pathType: Prefix
            backend:
              service:
                name: ai-service
                port:
                  name: http

          - path: /orders
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  name: http
