apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-image-updater
  namespace: argocd-image-updater
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-image-updater-role
  namespace: argocd-image-updater
rules:
  - apiGroups: ["", "apps", "argoproj.io"]
    resources: ["deployments", "rollouts", "replicasets", "pods"]
    verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-image-updater-rb
  namespace: argocd-image-updater
subjects:
  - kind: ServiceAccount
    name: argocd-image-updater
    namespace: argocd-image-updater
roleRef:
  kind: Role
  name: argocd-image-updater-role
  apiGroup: rbac.authorization.k8s.io