apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-image-updater
  namespace: argocd-image-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-image-updater
  template:
    metadata:
      labels:
        app: argocd-image-updater
    spec:
      serviceAccountName: argocd-image-updater
      containers:
        - name: argocd-image-updater
          image: argoprojlabs/argocd-image-updater:latest
          args:
            - --argocd-server
            - argocd-server.argocd.svc.cluster.local:443
            - --loglevel
            - info
          env:
            - name: ARGOCD_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argocd-secret
                  key: admin.password