apiVersion: v1
kind: Service
metadata:
  name: ai-service
  #  namespace: goormone-msa
  labels :
    app: ai-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: ai-service
