apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: goormone-msa
  labels :
    app: auth-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: auth-service
