apiVersion: v1
kind: Service
metadata:
  name: payment-service
#  namespace: goormone-msa
  labels:
    app: payment-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: payment-service