apiVersion: v1
kind: Service
metadata:
  name: store-service
#  namespace: goormone-msa
  labels:
    app: store-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: store-service