apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080   # 외부에서 접근할 포트
      protocol: TCP
    - name: agent
      port: 50000
      targetPort: 50000
      nodePort: 30500   # (선택사항) Jenkins 에이전트 연결용 포트
      protocol: TCP