apiVersion: v1
kind: Service
metadata:
  name: ai-service
  #  namespace: goormone-msa
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /ai/health
  labels :
    app: ai-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: ai-service
