apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-registries
  namespace: argocd
data:
  registries.yaml: |
    registries:
      - name: ecr
        api_url: 490913547024.dkr.ecr.ap-northeast-2.amazonaws.com
        prefix: 490913547024.dkr.ecr.ap-northeast-2.amazonaws.com
        credentials: ecr:aws_region=ap-northeast-2