apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-registries
  namespace: argocd
data:
  registries.conf: |-
    registries:
      - name: aws-ecr-apne2
        api_url: https://490913547024.dkr.ecr.ap-northeast-2.amazonaws.com
        prefix: 490913547024.dkr.ecr.ap-northeast-2.amazonaws.com
        default: true
        credentials: "ecr:role=arn:aws:iam::490913547024:role/eksctl-Groom-EKS-Cluster-addon-iamserviceacco-Role1-VEcAya4s4CwL,aws_region=ap-northeast-2"
